# Generated by Django 5.1 on 2024-10-20 05:56

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0001_initial'),
        ('taggit', '0009_remove_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
